server:
  port: 80
  servlet:
    context-path: /feng
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///mybatis-example
    username: root
    password: 51213002
    driver-class-name: com.mysql.cj.jdbc.Driver